apiVersion: apps/v1
kind: Deployment
metadata:
  name: adap-app01
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: adap-app01
  template:
    metadata:
      labels:
        app: adap-app01
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: adap-app01
        ports:
        - containerPort: 80
